version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: readfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: readfile_db
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
